[package]
name = "joss"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "JSON Operating System Schema"
license = "MIT"

[lib]
crate-type =["cdylib"]

[dependencies]
cstring="0.0.2"
